# Generated by Django 4.1.1 on 2022-11-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts_for_bot', '0003_sendedmessages_not_send_sendedmessages_success_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedmessages',
            name='planned_msg_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
